### PR TITLE
Fix SElinux enforcing

### PR DESCRIPTION
**Pull request by newAnim**
Perhaps that this is that?

### CODE REVIEW

**Comment by high1** [comment]
It could be. Cant test it right now - but it's worth to try.,

**Comment by newAnim** [comment]
I'm glad to hear it, I await news :)

**Comment by Narudgi** [comment]
I'm glad to hear it, I await news

**Comment by high1** [comment]
Stopped building CM12 for now - I want to fix what can be fixed in CM11.

**Comment by newAnim** [comment]
Okay

**Pull request merged**
